### ISSUE TITLE
Add README for TrueNAS Scale Configuration for nfsn-ddns

### ISSUE THREAD

**Issue by thatdecade** [jdknight/nfsn-ddns#1]
I really appreciate your nfsn-ddns app and the effort to make it available in Docker with environment variables. Reading the source code and configuring it for my setup was a joy 😃

I have created a guide for setting up and testing the `nfsn-ddns` application on TrueNAS Scale. Please consider adding it as `readme_truenasscale.md` 🙏

Thank you, let me know if any modifications are needed.

Best regards,  
Dustin

**Proposed Guide:**
```
# TRUENAS SERVER CONFIG

## Setup

**Login to NearlyFreeSpeech.net and get the API key**
- Member Interface > "Profile" tab > "Actions" > "Manage API Key"

**TrueNAS Scale > Datasets > Add Dataset**
- NFSN_DDNS_CONFIG

**TrueNAS Scale > Apps > Discover Apps > Custom App**
- Application Name: nfsn-ddns
- Image repo: ghcr.io/jdknight/nfsn-ddns
- Environment Variables:
  - NFSN_DDNS_API_LOGIN: example_username
  - NFSN_DDNS_API_TOKEN: example_token
  - NFSN_DDNS_DOMAINS: ddns.example.com
  - NFSN_DDNS_CACHE: 1
  - NFSN_DDNS_CACHE_FILE: /var/nfsn-ddns/cached-ip
- Storage: Add Host/Mount
  - Host Path: /mnt/Pool/NFSN_DDNS_CONFIG
  - Mount Path: /var/nfsn-ddns

## Testing

**Check the App Logs**
- Ensure that there are no errors and IP was sent to nfsn.

**Check the App Shell**
- `cat /var/nfsn-ddns/cached-ip`
- You should see your public IP cached in the file

**Log in to NearlyFreeSpeech.net and pull up the domain's DNS information**
- Ensure that ddns.example.com was added/updated

**If you have any ports open in your firewall (port forwarding), you can test they work with the new URL**

```

**Comment by jdknight** [comment]
Thanks for the suggestion. I have written this up into a proposed document based on your instructions:

https://github.com/jdknight/nfsn-ddns/blob/prospect-truenasscale-readme/README_TrueNAS_SCALE.md

If you would like to review and propose any changes on this, comments are welcome.

**Comment by thatdecade** [comment]
Looks great!
